#!/usr/bin/env bash
# Creates / fixes the EcoBinAI .env on the Pi so the Google AI Studio
# Gemma backend is used (no Ollama required).
#
# Usage:
#   bash scripts/configure_pi.sh YOUR_GOOGLE_AI_API_KEY
#
# Then restart uvicorn:
#   .venv/bin/uvicorn backend.api.main:app --host 0.0.0.0 --port 8000

set -e

if [ -z "$1" ]; then
  echo "❌  You need to pass your Google AI Studio API key as the first argument."
  echo "    Get one (free) at: https://aistudio.google.com/app/apikey"
  echo
  echo "    Then run:  bash scripts/configure_pi.sh AIzaSy..."
  exit 1
fi

KEY="$1"
ENV_FILE=".env"

# Always rewrite from scratch — guarantees a clean, correct file.
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/configure_pi.sh
# Edit any of these by hand if you need to.

# ── Gemma 4 backend (cloud) ──────────────────────────────────────────────────
GEMMA_BACKEND=google_ai_studio
GOOGLE_AI_API_KEY=$KEY
GEMMA_MODEL=gemma-4-26b-a4b-it

# ── Ollama (offline) — left here in case you want to switch later ────────────
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=gemma3:1b

# ── Hardware ─────────────────────────────────────────────────────────────────
HARDWARE_MODE=true
HARDWARE_DRIVER=pca9685
PCA9685_ADDRESS=0x40
PCA9685_FREQ_HZ=50
PCA9685_CHANNEL_RECYCLABLE=0
PCA9685_CHANNEL_COMPOST=4
PCA9685_CHANNEL_TRASH=8
PCA9685_CHANNEL_HAZARDOUS=12
SERVO_CLOSED_US=600
SERVO_OPEN_US=2400

# GPIO pins (only used when HARDWARE_DRIVER=gpio)
SERVO_PIN_RECYCLABLE=17
SERVO_PIN_COMPOST=27
SERVO_PIN_TRASH=22
SERVO_PIN_HAZARDOUS=10

# ── USB webcam (standalone bin mode) ─────────────────────────────────────────
USB_CAMERA_ENABLED=true
USB_CAMERA_INTERVAL_S=1.5
USB_CAMERA_SCENE_DIFF_THRESHOLD=12
CAMERA_INDEX=0
CAMERA_RESOLUTION_W=640
CAMERA_RESOLUTION_H=480

# ── App ──────────────────────────────────────────────────────────────────────
APP_HOST=0.0.0.0
APP_PORT=8000
DATABASE_URL=sqlite:///./ecobin.db
LID_OPEN_DURATION=3600
EOF

echo "✅  .env written. Verifying:"
echo "----"
grep -E '^(GEMMA_BACKEND|GEMMA_MODEL|GOOGLE_AI_API_KEY|HARDWARE_MODE|HARDWARE_DRIVER|USB_CAMERA_ENABLED)=' "$ENV_FILE" \
  | sed 's/\(GOOGLE_AI_API_KEY=\)\(.\{6\}\).*/\1\2…(redacted)/'
echo "----"
echo
echo "▶  Now restart the server (Ctrl+C the running one first):"
echo "    .venv/bin/uvicorn backend.api.main:app --host 0.0.0.0 --port 8000"
echo
echo "   You should see:"
echo "    EcoBinAI started | backend=google_ai_studio model=gemma-4-26b-a4b-it ..."
